"""Real PostgreSQL idempotency, isolation and rollback in a unique test schema."""

from __future__ import annotations

import os
import uuid
from dataclasses import replace
from datetime import UTC, date, datetime
from decimal import Decimal
from pathlib import Path

import psycopg2
import pyarrow as pa
import pyarrow.parquet as pq
import pytest
from psycopg2 import sql

from nyc_taxi_lakehouse.orchestration.state import ProcessingPeriod
from nyc_taxi_lakehouse.serving import publisher
from nyc_taxi_lakehouse.serving.config import ServingConfig
from nyc_taxi_lakehouse.serving.database import MARTS, Mart
from nyc_taxi_lakehouse.serving.publisher import gold_path, publish_period

pytestmark = pytest.mark.skipif(
    os.environ.get("RUN_SERVING_INTEGRATION") != "1",
    reason="Set RUN_SERVING_INTEGRATION=1 with the local analytics database running.",
)


@pytest.fixture()
def isolated_config() -> ServingConfig:
    base = ServingConfig.from_env()
    schema = f"serving_test_{uuid.uuid4().hex[:12]}"
    config = replace(base, schema=schema)
    try:
        yield config
    finally:
        # The target was generated by this fixture; never touch the real analytics schema.
        assert schema.startswith("serving_test_") and len(schema) == 25
        with psycopg2.connect(**base.connect_kwargs()) as connection:
            with connection.cursor() as cursor:
                cursor.execute(sql.SQL("DROP SCHEMA IF EXISTS {} CASCADE").format(
                    sql.Identifier(schema)))


def _synthetic_row(mart: Mart, period: ProcessingPeriod, trips: int = 2) -> dict[str, object]:
    values: dict[str, object] = {
        "pickup_date": date(period.year, period.month, 15), "pickup_hour": 12,
        "pickup_location_id": 161, "payment_type": 1, "trip_count": trips,
        "total_revenue": Decimal("25.00"), "total_tip_amount": Decimal("3.00"),
        "total_trip_distance": 8.0, "average_trip_distance": 4.0,
        "average_trip_duration_minutes": Decimal("15.250000"),
        "average_fare_amount": Decimal("10.000000"),
        "average_total_amount": Decimal("12.500000"),
        "average_tip_amount": Decimal("1.500000"),
        "average_revenue_per_trip": Decimal("12.500000"),
        "trip_percentage": 100.0, "revenue_percentage": 100.0,
        "_gold_processed_at": datetime(2024, 1, 1, tzinfo=UTC).replace(tzinfo=None),
        "_source_taxi_type": "yellow", "_source_year": period.year,
        "_source_month": period.month, "borough": "Manhattan", "zone": "Midtown Center",
        "service_zone": "Yellow Zone",
    }
    return {name: values[name] for name in mart.names}


def _write_gold(root: Path, period: ProcessingPeriod, *, trips: int = 2,
                duplicate_daily: bool = False) -> None:
    for mart in MARTS:
        path = gold_path(root, mart, "yellow", period)
        path.mkdir(parents=True, exist_ok=True)
        row = _synthetic_row(mart, period, trips)
        rows = [row, row.copy()] if duplicate_daily and mart.name == "daily_trip_metrics" else [row]
        pq.write_table(pa.Table.from_pylist(rows), path / "part-00000.parquet")


def _snapshot(config: ServingConfig, period: ProcessingPeriod) -> dict[str, tuple[int, int]]:
    with psycopg2.connect(**config.connect_kwargs()) as connection:
        with connection.cursor() as cursor:
            values = {}
            for mart in MARTS:
                cursor.execute(sql.SQL("SELECT count(*),sum(trip_count) FROM {}.{} "
                                       "WHERE _source_year=%s AND _source_month=%s").format(
                    sql.Identifier(config.schema), sql.Identifier(mart.name)),
                    (period.year, period.month))
                values[mart.name] = cursor.fetchone()
            return values


def test_real_postgres_period_replacement_and_rollback(
    isolated_config: ServingConfig, tmp_path: Path
) -> None:
    january = ProcessingPeriod(2024, 1)
    february = ProcessingPeriod(2024, 2)
    _write_gold(tmp_path, january)
    _write_gold(tmp_path, february)
    first = publish_period(isolated_config, january, gold_dir=tmp_path)
    assert len(first.marts) == 5
    assert all(item.trip_count == 2 for item in first.marts.values())
    publish_period(isolated_config, february, gold_dir=tmp_path)
    january_before = _snapshot(isolated_config, january)
    february_before = _snapshot(isolated_config, february)

    publish_period(isolated_config, january, gold_dir=tmp_path)
    assert _snapshot(isolated_config, january) == january_before
    assert _snapshot(isolated_config, february) == february_before

    _write_gold(tmp_path, january, trips=3)
    publish_period(isolated_config, january, gold_dir=tmp_path)
    assert all(total == 3 for _, total in _snapshot(isolated_config, january).values())
    assert _snapshot(isolated_config, february) == february_before
    prior_good = _snapshot(isolated_config, january)

    _write_gold(tmp_path, january, duplicate_daily=True)
    with pytest.raises(psycopg2.errors.UniqueViolation):
        publish_period(isolated_config, january, gold_dir=tmp_path)
    assert _snapshot(isolated_config, january) == prior_good
    assert _snapshot(isolated_config, february) == february_before


def test_five_mart_insert_failure_rolls_back_then_retry_is_idempotent(
    isolated_config: ServingConfig, tmp_path: Path, monkeypatch: pytest.MonkeyPatch,
) -> None:
    january, february = ProcessingPeriod(2024, 1), ProcessingPeriod(2024, 2)
    _write_gold(tmp_path, january)
    _write_gold(tmp_path, february)
    publish_period(isolated_config, january, gold_dir=tmp_path)
    publish_period(isolated_config, february, gold_dir=tmp_path)
    previous_january = _snapshot(isolated_config, january)
    previous_february = _snapshot(isolated_config, february)
    _write_gold(tmp_path, january, trips=3)
    real_insert = publisher.execute_values
    attempts = 0

    def fail_third_insert(*args: object, **kwargs: object) -> None:
        nonlocal attempts
        attempts += 1
        if attempts == 3:
            raise RuntimeError("injected insert fault in third mart")
        real_insert(*args, **kwargs)

    with monkeypatch.context() as fault:
        fault.setattr(publisher, "execute_values", fail_third_insert)
        with pytest.raises(RuntimeError, match="third mart"):
            publish_period(isolated_config, january, gold_dir=tmp_path)
    assert attempts == 3
    assert _snapshot(isolated_config, january) == previous_january
    assert _snapshot(isolated_config, february) == previous_february

    recovered = publish_period(isolated_config, january, gold_dir=tmp_path)
    assert all(item.trip_count == 3 for item in recovered.marts.values())
    after_recovery = _snapshot(isolated_config, january)
    assert _snapshot(isolated_config, february) == previous_february
    publish_period(isolated_config, january, gold_dir=tmp_path)
    assert _snapshot(isolated_config, january) == after_recovery


def test_postgres_connection_outage_preserves_other_layers_and_recovers(
    isolated_config: ServingConfig, tmp_path: Path,
) -> None:
    january = ProcessingPeriod(2024, 1)
    _write_gold(tmp_path, january)
    publish_period(isolated_config, january, gold_dir=tmp_path)
    before = _snapshot(isolated_config, january)
    gold_file = gold_path(tmp_path, MARTS[0], "yellow", january) / "part-00000.parquet"
    gold_before = gold_file.read_bytes()
    _write_gold(tmp_path, january, trips=3)
    with pytest.raises(psycopg2.OperationalError):
        publish_period(replace(isolated_config, port=1), january, gold_dir=tmp_path)
    assert _snapshot(isolated_config, january) == before
    assert gold_file.is_file() and gold_file.read_bytes() != gold_before
    publish_period(isolated_config, january, gold_dir=tmp_path)
    assert all(trips == 3 for _, trips in _snapshot(isolated_config, january).values())
